[package]
name = "fileorganizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
rocket_dyn_templates = { version = "0.1.0-rc.2", features = ["tera"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
